version: "3.9"

services:
    db:
        container_name: db
        image: posgres:14
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
