import Provider from "@/app/_trpc/Provider";
import "@/app/globals.css";
import cn from "@/libs/cn";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Open_Sans, Roboto } from "next/font/google";

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    variable: "--font-roboto",
    display: "swap",
});
const open_sans = Open_Sans({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-open-sans",
    display: "swap",
});

export const metadata = {
    title: "TuneUp",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
}

const BaseLayout = ({ children }: Props) => {
    return (
        <ClerkProvider appearance={{ baseTheme: dark }}>
            <Provider>
                <html
                    lang="en"
                    className={cn(roboto.variable, open_sans.variable)}
                >
                    <body>
                        <div className="min-h-screen w-full overflow-x-hidden">
                            {children}
                        </div>
                    </body>
                </html>
            </Provider>
        </ClerkProvider>
    );
};

export default BaseLayout;
