#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Testing and 🔎 Searching for mistakes in your code."
npx lint-staged
echo "✅✅✅ Well done🎊 Let me run the Build once 🛠️"
pnpm run build
echo "✅✅✅ Great Work🎊 Build Successfull ✨ Accepting your Commit This Time ✅✅❤️"
