# name: Vercel Preview Deployment
# env:
#     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# on:
#     pull_request:
#         types: [closed]
#         branches:
#             - dev
# jobs:
#     Deploy-Preview:
#         if: github.event.pull_request.merged == true
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - name: Install Vercel CLI
#               run: npm install --global vercel@latest
#             - name: Pull Vercel Environment Information
#               run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
#             - name: Build Project Artifacts
#               run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
#             - name: Deploy Project Artifacts to Vercel
#               run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

name: CF Preview Deployment
on:
    pull_request:
        types: [closed]
        branches:
            - dev
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish to Cloudflare Pages
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              run: npx @cloudflare/next-on-pages@1

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: ${{ secrets.CF_PROJECT_NAME }}
                  directory: YOUR_ASSET_DIRECTORY
                  branch: dev
                  workingDirectory: .vercel/output/static
                  wranglerVersion: "3"
